server:
  port: 8081
  servlet:
    encoding:
      charset: UTF-8
      force: true

spring:
  datasource:
    url: jdbc:postgresql://3.39.234.47:5432/youf
    driver-class-name: org.postgresql.Driver
    username: admin
    password: admin1234
    hikari:
      connection-timeout: 30000       # 연결 타임아웃: 30초
      maximum-pool-size: 10           # 최대 연결 풀 크기
      minimum-idle: 5                 # 최소 유휴 연결 수
      idle-timeout: 300000            # 유휴 연결 타임아웃: 5분
      max-lifetime: 1200000           # 연결 최대 수명: 20분
      connection-test-query: SELECT 1 # 연결 테스트 쿼리
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        order_inserts: true
        order_updates: true
      '[hibernate.default_batch_fetch_size]': 100
      '[hibernate.format_sql]': true
      '[hibernate.query.timeout]': 10000  # 쿼리 타임아웃: 10초
      '[hibernate.jdbc.timeout]': 10  # 초 단위
    show-sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 830719346682-3mpsdtr9tpka8nr95us4k2ok3r1bgpnp.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
quartz:
  job-store-type: jdbc
  jdbc:
    initialize-schema: always # 실행 시 테이블 자동 생성 (운영 환경에서는 별도 관리 권장)
  properties:
    org:
      quartz:
        scheduler:
          instanceName: QuartzScheduler
        jobStore:
          class: org.quartz.impl.jdbcjobstore.JobStoreTX
          driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
        threadPool:
          threadCount: 5
  output:
    ansi:
      enabled: always
file:
  upload-dir: /home/ubuntu/youf/file  # 원하는 저장 경로 설정

logging:
  level:
    com:
      uf:
        assistance:
          config:
            env: TRACE
    com.uf.assistance: DEBUG
    org.hibernate.orm.jdbc.bind: DEBUG
    org.springframework.web.socket: DEBUG
    org.springframework.messaging: DEBUG
    org.springframework.web.SimpLogging: DEBUG
    org:
      hibernate:
        SQL: TRACE
        type:
          descriptor:
            sql:
              BasicBinder: TRACE